apiVersion: apps/v1
kind: Deployment
metadata:
  name: newrelic-metadata-injection-deployment
  namespace: default
  labels:
    app: newrelic-metadata-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newrelic-metadata-injection
  template:
    metadata:
      labels:
        app: newrelic-metadata-injection
    spec:
      serviceAccountName: newrelic-metadata-injection-service-account
      containers:
      - name: metadata-injector
        image: newrelic/k8s-metadata-injection:1.1.0
        env:
        - name: clusterName
          value: "New Relic Push Game"
        volumeMounts:
        - name: tls-key-cert-pair
          mountPath: /etc/tls-key-cert-pair
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
      volumes:
      - name: tls-key-cert-pair
        secret:
          secretName: newrelic-metadata-injection-secret
---
apiVersion: v1
kind: Service
metadata:
  name: newrelic-metadata-injection-svc
  namespace: default
  labels:
    app: newrelic-metadata-injection
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: newrelic-metadata-injection
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: newrelic-metadata-injection-cfg
  labels:
    app: newrelic-metadata-injection
webhooks:
- name: metadata-injection.newrelic.com
  clientConfig:
    service:
      name: newrelic-metadata-injection-svc
      namespace: default
      path: "/mutate"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYU82UTBhZHJUOW93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpBNU1UWXhNVEUxTVRaYUZ3MHpNekE1TVRNeE1URTFNVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNkSmhNUlBwbjhHNy9DN0NyNlVnaEFyVmZqa3RwTTRlc2RrQVYvTURVOFlaMVlTTm52ZlVrN3pjeG0KeUF1QVFWRFlmaTNQOHRRZmo5NmRVRlJLb1lrMW1oTE5heFhvMDNzakhaeG9WK2RzSllEcXE4M1JvNkJLaDJBNApUdzc2bDRTZ2RacEI0c0xDcEg3VG9RUWpXRGJrTk96NUsvakJkRk80cVZLVlorUGJhbTNCUkJzT3creVFBNXloCjFqTkx2NHlXWmdlbTBSRng1VURuajVReHYzL0pTTDFCR29ERi9vVlgyVFVJS2pzSTg5YTljNm9Dd2dheGlWakUKZFpXeDlzRUFYSjdCaVRaOWNMTWtyS2dOZGRja3lkRnJkbXJGUmpySDBNVjdWMUV3cCtQcy9idUc1ajk5UWRLUApOZzViYzI1akZPWHQvbW16aWJjaURvZDM4dmdwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSSC91ZlRZdldsTXZlam1GYnBLMU1uUWdCSW1EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnhuN21Tb3lHMQo3QVBQOUlGRlBjNTR3RFg4Mm5HVm51N3E2NFVpcmd3b3hvaEY2ZUpKbHZFdVNQaC9MMTZsaUI4ZkNnNkc2cWFFCnkrVlJHZi9iYyt3TVZIZ2RPT3hMZTQ2MG5VdDg4SXNFSFRYMmEySzZjc3NGYmF5TFZsSkZNYXNJbVg0OEg1TEMKaWQ3TmN6aXYwUlBhTm5yem05QUROakRlR2tWbGlLSEt2TXZJYldiWVMyRGRwUFhoY3p3cGlEdm0rTHRaZ1VVSApFUkFaRVpaTXpkcDR4L1JLSytsWmdHanlzYzc4ZFEzUTB1T3RoYzRuNkRDVDRaUE9oMDN0amZGT2tBOE4rSHVaCk9BeWF0Qm5OWlRRakh3SDExR29pTXNZbTNEOEI4ci9kUHdSUmV6N0FQajU2N0ttWDlHTW9UY3VoVkZjYWNZZ3kKaW5QMVNKcVJLdVBqCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Ignore
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic-metadata-injection-service-account
  namespace: default
  labels:
    app: newrelic-metadata-injection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic-metadata-injection-cluster-role
  labels:
    app: newrelic-metadata-injection
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "create", "patch"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests/approval"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic-metadata-injection-cluster-role-binding
  labels:
    app: newrelic-metadata-injection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic-metadata-injection-cluster-role
subjects:
  - kind: ServiceAccount
    name: newrelic-metadata-injection-service-account
    namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: newrelic-metadata-setup
  labels:
    app: newrelic-metadata-setup
spec:
  template:
    spec:
      serviceAccountName: newrelic-metadata-injection-service-account
      containers:
      - name: metadata-cert-setup
        image: newrelic/k8s-webhook-cert-manager:1.0.1
        command: ["./generate_certificate.sh"]
        args:
          - "--service"
          - "newrelic-metadata-injection-svc"
          - "--webhook"
          - "newrelic-metadata-injection-cfg"
          - "--secret"
          - "newrelic-metadata-injection-secret"
          - "--namespace"
          - "default"
      restartPolicy: Never
  backoffLimit: 1
