apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: demo
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: demo
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
        tier: frontend
    spec:
      containers:
      - name: frontend
        #image: docker.io/spolfliet/newrelic-k8s-guestbook-frontend:latest
        image: polfliet/newrelic-kubernetes-demo:latest
        imagePullPolicy: Never 
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: guestbook-secret
              key: new_relic_license_key
        - name: NEW_RELIC_APP_NAME
          value: New Relic Kubernetes Demo - Frontend
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env      
        ports:
          - containerPort: 3000
