---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: game-auth
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: game
        tier: auth
    spec:
      containers:
      - name: auth 
        image: busybox
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secret
              key: new_relic_license_key
        - name: NEW_RELIC_APP_NAME
          value: FutureStack Game - Auth
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env      
        ports:
          - containerPort: 3000
