apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game
      tier: frontend
  template:
    metadata:
      labels:
        app: game
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/spolfliet/newrelic-interactive-demo-frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secret
              key: new_relic_license_key
        - name: NEW_RELIC_APP_NAME
          value: FutureStack Game - Frontend
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GET_HOSTS_FROM
          value: dns
        ports:
          - containerPort: 3000
