# This is just a dummy service to populate the Kubernetes cluster explorer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: game-analytics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: game
        tier: analytics
    spec:
      containers:
      - name: analytics
        image: docker.io/spolfliet/newrelic-interactive-demo-analytics:unknown
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secret
              key: new_relic_license_key
        - name: NEW_RELIC_APP_NAME
          value: FutureStack Game - Analytics
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env      
        ports:
          - containerPort: 3000
